/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chiefy;

/**
 *
 * @author REDHAT
 */
public class test extends javax.swing.JFrame {
    public double hrgSPP,hrgGedung,hrgModul,hrgUTS,hrgUAS,hrgUPM;
    public int bulan = 0;
    public String npm;
    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }
    
    public test(String npm) {
        initComponents();
        this.npm = npm;
        lblNPM.setText(this.npm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spp = new javax.swing.JCheckBox();
        modul = new javax.swing.JCheckBox();
        gedung = new javax.swing.JCheckBox();
        uts = new javax.swing.JCheckBox();
        uas = new javax.swing.JCheckBox();
        upm = new javax.swing.JCheckBox();
        pilih = new javax.swing.JComboBox<>();
        sumHarga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        lblNPM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pilihan Pembayaran"));

        spp.setText("SPP");
        spp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sppStateChanged(evt);
            }
        });

        modul.setText("Modul");
        modul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                modulStateChanged(evt);
            }
        });

        gedung.setText("Gedung");
        gedung.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gedungStateChanged(evt);
            }
        });

        uts.setText("UTS");
        uts.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                utsStateChanged(evt);
            }
        });

        uas.setText("UAS");
        uas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                uasStateChanged(evt);
            }
        });

        upm.setText("UPM");
        upm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                upmStateChanged(evt);
            }
        });

        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "2", "4", "6" }));
        pilih.setEnabled(false);
        pilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihItemStateChanged(evt);
            }
        });
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        sumHarga.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sumHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setText("Bulan");

        hitung.setText("Proceed");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spp)
                        .addGap(26, 26, 26)
                        .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(hitung))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uts)
                            .addComponent(modul)
                            .addComponent(gedung)
                            .addComponent(upm)
                            .addComponent(uas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sumHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spp)
                    .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(hitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(modul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gedung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upm))
                    .addComponent(sumHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblNPM.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNPM)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihActionPerformed

    private void sppStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sppStateChanged
        // TODO add your handling code here:
        if(this.spp.isSelected()) {
            pilih.setEnabled(true);
            this.hrgSPP = 300000;
        } else {
            pilih.setEnabled(false);
            this.hrgSPP = 0;
        }
    }//GEN-LAST:event_sppStateChanged

    private void pilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihItemStateChanged
        // TODO add your handling code here:
        this.bulan = (int) pilih.getSelectedIndex();
    }//GEN-LAST:event_pilihItemStateChanged

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double total;
        this.hrgSPP *= this.bulan;
        
        total = this.hrgSPP + this.hrgGedung + this.hrgModul + this.hrgUTS + this.hrgUAS + this.hrgUPM;
        sumHarga.setText(""+total);
    }//GEN-LAST:event_hitungActionPerformed

    private void modulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_modulStateChanged
        // TODO add your handling code here:
         if(this.modul.isSelected()) {
            this.hrgModul = 300000;
        } else {
            this.hrgModul = 0;
        }
    }//GEN-LAST:event_modulStateChanged

    private void gedungStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gedungStateChanged
        // TODO add your handling code here:
        if(this.gedung.isSelected()) {
            this.hrgGedung = 1200000;
        } else {
            this.hrgGedung = 0;
        }
        
    }//GEN-LAST:event_gedungStateChanged

    private void utsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_utsStateChanged
        // TODO add your handling code here:
        if(this.uts.isSelected()) {
            this.hrgUTS = 150000;
        } else {
            this.hrgUTS = 0;
        }
    }//GEN-LAST:event_utsStateChanged

    private void uasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_uasStateChanged
        // TODO add your handling code here:
        if(this.uas.isSelected()) {
            this.hrgUAS = 150000;
        } else {
            this.hrgUAS = 0;
        }
    }//GEN-LAST:event_uasStateChanged

    private void upmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_upmStateChanged
        // TODO add your handling code here:
        if(this.upm.isSelected()) {
            this.hrgUPM = 150000;
        } else {
            this.hrgUPM = 0;
        }
    }//GEN-LAST:event_upmStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox gedung;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNPM;
    private javax.swing.JCheckBox modul;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JCheckBox spp;
    private javax.swing.JLabel sumHarga;
    private javax.swing.JCheckBox uas;
    private javax.swing.JCheckBox upm;
    private javax.swing.JCheckBox uts;
    // End of variables declaration//GEN-END:variables
}
